queue_rules:
  - name: default
    queue_conditions:
      - check-success = validate-pr
    merge_conditions:
      - check-success = e2e
merge_queue:
  max_parallel_checks: 1
  reset_on_external_merge: never
