name: Validate pull request before putting into queue

on:
  pull_request:
    branches: 
      - 'main'

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: e2e1.sh
      run: |-
        echo "$(basename "$0")"
        echo "Running e2e1.sh script"
        sleep 300
        exit 0
    - name: e2e2.sh
      run: |-
        echo "$(basename "$0")"
        echo "Running e2e2.sh script"
        sleep 300
        echo "passed e2e2.sh script"
        exit 0

    